### ISSUE TITLE
Issues in running the project 

### ISSUE THREAD

**Issue by karamat552** [jagadeesh-k-2802/blood-donation-app-flutter#1]
Can u elaborate the steps for mongodb part and firebase

**Comment by jagadeesh-k-2802** [comment]
1. Create a MongoDB Database in the Cloud
 - Head to [MongoDB Atlas](https://www.mongodb.com/cloud/atlas) and sign in or create a new account.
 - Set up a new cluster and configure the database as per your project needs.
 - Once the cluster is created, retrieve the connection string from the Database Access section in MongoDB Atlas.
 - Update your .env file by adding the MongoDB connection string in the following format: `MONGO_URI=<connection-string>`

2. Firebase Admin SDK (Server-side)
- Go to the Firebase Console and navigate to your project
- Under Project Settings > Service Accounts, generate a new private key
- Download the JSON file containing the Firebase Admin Private Key
- Place this file inside your project directory at: `/server/config/` with renamed to `firebase-admin.json`

3. Firebase (Client-side)
- Install flutterfire CLI `dart pub global activate flutterfire_cli`
- Install firebase CLI using NPM `npm install -g firebase-tools`
- Configure firebase using your own firebase project `cd mobile && flutterfire configure`


While GitHub issues can be a good place to ask questions regarding specific problems, errors, or bugs encountered during setup or running the app, it might not be the best place for general questions about how to run the app from scratch.

Thanks
